/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import edu.neu.ui.createpanel.CreateDemographicJPanel;
import edu.neu.ui.createpanel.CreateBankAccountJPanel;
import edu.neu.ui.createpanel.CreateDriverLicenseJPanel;
import edu.neu.ui.report.ViewPersonReportJPanel;
import model.DemographicDetails;
//import model.DemographicDetails;
import model.Person;

/**
 *
 * @author juhip
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;
    DemographicDetails demodetails;
    public MainJFrame() {
        initComponents();
        person = new Person();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        lblPerson = new javax.swing.JLabel();
        labelDemo = new javax.swing.JButton();
        lableAccount = new javax.swing.JButton();
        lableLicense = new javax.swing.JButton();
        lableAddress = new javax.swing.JButton();
        lableMedical = new javax.swing.JButton();
        lbleReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        lblPerson.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblPerson.setText("Person");

        labelDemo.setText("Demographic");
        labelDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelDemoActionPerformed(evt);
            }
        });

        lableAccount.setText("Bank Account");
        lableAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lableAccountActionPerformed(evt);
            }
        });

        lableLicense.setText("Driver's License");
        lableLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lableLicenseActionPerformed(evt);
            }
        });

        lableAddress.setText("Address");
        lableAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lableAddressActionPerformed(evt);
            }
        });

        lableMedical.setText("Medical");
        lableMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lableMedicalActionPerformed(evt);
            }
        });

        lbleReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbleReport.setText("Generate Report with all the details");
        lbleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbleReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbleReport, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbleReport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDemo)
                .addGap(18, 18, 18)
                .addComponent(lableAddress)
                .addGap(8, 8, 8)
                .addComponent(lableAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lableLicense)
                .addGap(18, 18, 18)
                .addComponent(lableMedical)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(417, 400));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    CreateDemographicJPanel demographicDetails;
    private void labelDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelDemoActionPerformed
         demographicDetails = new CreateDemographicJPanel();
         jSplitPane1.setRightComponent(demographicDetails);

        
    }//GEN-LAST:event_labelDemoActionPerformed

    private void lableAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lableAccountActionPerformed
        CreateBankAccountJPanel bankAccountDet= new CreateBankAccountJPanel();
        jSplitPane1.setRightComponent(bankAccountDet);
    }//GEN-LAST:event_lableAccountActionPerformed

    private void lableLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lableLicenseActionPerformed
        // TODO add your handling code here:
        CreateDriverLicenseJPanel license = new CreateDriverLicenseJPanel();
        jSplitPane1.setRightComponent(license);
    }//GEN-LAST:event_lableLicenseActionPerformed

    private void lableAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lableAddressActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lableAddressActionPerformed

    private void lableMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lableMedicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lableMedicalActionPerformed

    private void lbleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbleReportActionPerformed
                  // person.setLicenseNum(textLicenseNum.getText());           
        ViewPersonReportJPanel viewPerson = new ViewPersonReportJPanel(person,demodetails);
        jSplitPane1.setRightComponent(viewPerson);
         
    }//GEN-LAST:event_lbleReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton labelDemo;
    private javax.swing.JButton lableAccount;
    private javax.swing.JButton lableAddress;
    private javax.swing.JButton lableLicense;
    private javax.swing.JButton lableMedical;
    private javax.swing.JLabel lblPerson;
    private javax.swing.JButton lbleReport;
    // End of variables declaration//GEN-END:variables
}
