/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.ui.createpanel;

import edu.neu.ui.viewframes.ViewBankAccountJFrame;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import model.BankAccount;

/**
 *
 * @author juhip
 */
public class CreateBankAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateBankAccountJPanel
     */
    BankAccount bankAcct;
    
    public CreateBankAccountJPanel() {
        initComponents();
        bankAcct = new BankAccount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelBankName = new javax.swing.JLabel();
        labelAcctNum = new javax.swing.JLabel();
        labelBankRoutingNum = new javax.swing.JLabel();
        labelBankAccountBal = new javax.swing.JLabel();
        labelAcctType = new javax.swing.JLabel();
        textBankName = new javax.swing.JTextField();
        textBankRoutingNum = new javax.swing.JTextField();
        textBankAcctBal = new javax.swing.JTextField();
        textAcctNum = new javax.swing.JTextField();
        textAcctType = new javax.swing.JTextField();
        btnAcctSave = new javax.swing.JButton();
        comboCheckinSaving = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(500, 436));

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("Enter Bank Account Details");

        labelBankName.setText("Bank Name");

        labelAcctNum.setText("Account Number");

        labelBankRoutingNum.setText("Bank Routing Num");

        labelBankAccountBal.setText("Bank Account Balance");

        labelAcctType.setText("Account Type");

        textBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBankNameActionPerformed(evt);
            }
        });

        textBankRoutingNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBankRoutingNumActionPerformed(evt);
            }
        });

        textBankAcctBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBankAcctBalActionPerformed(evt);
            }
        });

        textAcctNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAcctNumActionPerformed(evt);
            }
        });

        textAcctType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAcctTypeActionPerformed(evt);
            }
        });

        btnAcctSave.setText("Save");
        btnAcctSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcctSaveActionPerformed(evt);
            }
        });

        comboCheckinSaving.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Saving" }));
        comboCheckinSaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCheckinSavingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelAcctNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelBankRoutingNum, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(labelBankAccountBal, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(124, 124, 124))
                    .addComponent(btnAcctSave)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelAcctType, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCheckinSaving, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textBankName)
                    .addComponent(textBankRoutingNum, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(textBankAcctBal, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(textAcctNum, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(textAcctType))
                .addGap(352, 352, 352))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBankName)
                    .addComponent(textBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcctNum)
                    .addComponent(textAcctNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBankRoutingNum)
                    .addComponent(textBankRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBankAccountBal)
                    .addComponent(textBankAcctBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAcctType)
                        .addComponent(comboCheckinSaving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textAcctType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnAcctSave)
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBankNameActionPerformed

    private void textBankRoutingNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBankRoutingNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBankRoutingNumActionPerformed

    private void textBankAcctBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBankAcctBalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBankAcctBalActionPerformed

    private void textAcctNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAcctNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAcctNumActionPerformed

    private void textAcctTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAcctTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAcctTypeActionPerformed

    private void btnAcctSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcctSaveActionPerformed
        bankAcct.setBankName(textBankName.getText());
        bankAcct.setAccountType(textAcctType.getText());
        bankAcct.setBankAccBalance(parseDouble(textBankAcctBal.getText()) );
        bankAcct.setBankRoutingNum(parseInt(textBankRoutingNum.getText()));
        
        JOptionPane.showMessageDialog(this, "Bank Account details are saved");
        ViewBankAccountJFrame viewBankAcct= new ViewBankAccountJFrame(bankAcct);
        viewBankAcct.setVisible(true);
        
    }//GEN-LAST:event_btnAcctSaveActionPerformed

    private void comboCheckinSavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCheckinSavingActionPerformed
        String selectedValue= comboCheckinSaving.getSelectedItem().toString();
        textAcctType.setText(selectedValue);
    }//GEN-LAST:event_comboCheckinSavingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcctSave;
    private javax.swing.JComboBox<String> comboCheckinSaving;
    private javax.swing.JLabel labelAcctNum;
    private javax.swing.JLabel labelAcctType;
    private javax.swing.JLabel labelBankAccountBal;
    private javax.swing.JLabel labelBankName;
    private javax.swing.JLabel labelBankRoutingNum;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textAcctNum;
    private javax.swing.JTextField textAcctType;
    private javax.swing.JTextField textBankAcctBal;
    private javax.swing.JTextField textBankName;
    private javax.swing.JTextField textBankRoutingNum;
    // End of variables declaration//GEN-END:variables
}
