/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.ui.createpanel;

import edu.neu.ui.viewframes.ViewDriverLicenseJFrame;
import java.util.Date;
import javax.swing.JOptionPane;
import model.DriverLicense;

/**
 *
 * @author juhip
 */
 
public class CreateDriverLicenseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDriverLicenseJPanel
     */
     DriverLicense driverLicense;
    public CreateDriverLicenseJPanel() {
        initComponents();
        driverLicense = new DriverLicense();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        lbDateOfIssue = new javax.swing.JLabel();
        lbleDateOfExpiry = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        textLicenseNum = new javax.swing.JTextField();
        textDateOfIssue = new javax.swing.JTextField();
        textDateOfExpiry = new javax.swing.JTextField();
        textBloodType = new javax.swing.JTextField();
        lblPicture = new javax.swing.JLabel();
        textPicture = new javax.swing.JTextField();
        btnLicenseSave = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 550));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Enter Driver's License Details");

        lblLicenseNumber.setText("License Number");

        lbDateOfIssue.setText("Date Of Issue");

        lbleDateOfExpiry.setText("Date Of Expiry");

        lblBloodType.setText("Blood Type");

        textLicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLicenseNumActionPerformed(evt);
            }
        });

        textDateOfIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateOfIssueActionPerformed(evt);
            }
        });

        textDateOfExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateOfExpiryActionPerformed(evt);
            }
        });

        textBloodType.setPreferredSize(new java.awt.Dimension(10, 20));
        textBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBloodTypeActionPerformed(evt);
            }
        });

        lblPicture.setText("Picture");

        textPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPictureActionPerformed(evt);
            }
        });

        btnLicenseSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLicenseSave.setText("Save");
        btnLicenseSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenseSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(lbDateOfIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbleDateOfExpiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDateOfExpiry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBloodType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textPicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLicenseSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNumber)
                    .addComponent(textLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateOfIssue)
                    .addComponent(textDateOfIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbleDateOfExpiry)
                    .addComponent(textDateOfExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBloodType)
                    .addComponent(textBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(textPicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnLicenseSave)
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textLicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLicenseNumActionPerformed

    private void textDateOfIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateOfIssueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDateOfIssueActionPerformed

    private void textDateOfExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateOfExpiryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDateOfExpiryActionPerformed

    private void textBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBloodTypeActionPerformed

    private void textPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPictureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPictureActionPerformed

    private void btnLicenseSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenseSaveActionPerformed
        driverLicense.setLicenseNum(textLicenseNum.getText());
        driverLicense.setDateOfIssuence(textDateOfIssue.getText());
        driverLicense.setDateOfExpiration(textDateOfExpiry.getText());
        driverLicense.setBloodType(textBloodType.getText());
        driverLicense.setPicture(textPicture.getText());
        
        JOptionPane.showMessageDialog(this, "Driver License details are saved");
        
        ViewDriverLicenseJFrame viewLicense= new ViewDriverLicenseJFrame(driverLicense);
        viewLicense.setVisible(true);
        
    }//GEN-LAST:event_btnLicenseSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLicenseSave;
    private javax.swing.JLabel lbDateOfIssue;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbleDateOfExpiry;
    private javax.swing.JTextField textBloodType;
    private javax.swing.JTextField textDateOfExpiry;
    private javax.swing.JTextField textDateOfIssue;
    private javax.swing.JTextField textLicenseNum;
    private javax.swing.JTextField textPicture;
    // End of variables declaration//GEN-END:variables
}
